services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file: .env.docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    container_name: user_service
    build:
      context: ../..
      dockerfile: ./services/user-service/Dockerfile
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10:10"      # HTTP port
      - "50000:50000"  # gRPC port

volumes:
  pgdata:
