env: "dev"

server:
  host: "0.0.0.0"
  port: "200"
  debug: true

grpc:
  host: "0.0.0.0"
  port: 50200
  max_concurrent_streams: 100
  keepalive:
    time: 60s
    timeout: 20s
  tls:
    enabled: true
    cert_file: "/path/to/cert.pem"
    key_file:  "/path/to/key.pem"

database:
  driver: "postgres"
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
  sslmode: "disable"

security:
  allowed_origins:
    - "http://localhost:3000"

logging:
  level: "debug"
  format: "json"